services:
  - type: web
    name: MiddlemanSafePlace
    env: docker
    branch: cloudflare/workers-autoconfig
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    instanceCount: 1
    instanceType: starter
